#!/usr/bin/env python3
"""Build the complete WanderWise notebook by adding all remaining modules."""

import json

def add_module3_cells():
    """Module 3: K-Means Clustering cells."""
    return [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 5. Module 3: Geographic Clustering (K-Means)\n",
                "\n",
                "Group POIs into days using K-Means clustering (K = number of days)."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Check if we have enough POIs for clustering\n",
                "if len(filtered_df) < NUM_DAYS:\n",
                "    raise ValueError(f\"Not enough POIs ({len(filtered_df)}) for {NUM_DAYS} days. Reduce NUM_DAYS or loosen filter.\")\n",
                "\n",
                "# Prepare coordinates for clustering\n",
                "coords = filtered_df[['latitude', 'longitude']].values\n",
                "\n",
                "# Apply K-Means clustering\n",
                "kmeans = KMeans(n_clusters=NUM_DAYS, random_state=42, n_init=10)\n",
                "filtered_df['cluster'] = kmeans.fit_predict(coords)\n",
                "\n",
                "# Assign cluster to day (cluster 0 -> day 1, cluster 1 -> day 2, etc.)\n",
                "filtered_df['day'] = filtered_df['cluster'] + 1\n",
                "\n",
                "# Calculate cluster statistics\n",
                "cluster_stats = filtered_df.groupby('day').agg({\n",
                "    'name': 'count',\n",
                "    'latitude': 'mean',\n",
                "    'longitude': 'mean',\n",
                "    'popularity_score': ['max', 'mean']\n",
                "}).round(4)\n",
                "\n",
                "print(f\"🗺️  K-Means Clustering Results (K={NUM_DAYS}):\")\n",
                "print(f\"\\n📊 POIs per Day:\")\n",
                "for day in range(1, NUM_DAYS + 1):\n",
                "    day_pois = filtered_df[filtered_df['day'] == day]\n",
                "    print(f\"   Day {day}: {len(day_pois)} POIs (centroid: {day_pois['latitude'].mean():.3f}, {day_pois['longitude'].mean():.3f})\")\n",
                "\n",
                "print(f\"\\n✅ Module 3 complete: POIs clustered into {NUM_DAYS} days\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Normalize popularity within each cluster for GA fitness\n",
                "# This ensures fair comparison between days\n",
                "for day in range(1, NUM_DAYS + 1):\n",
                "    day_mask = filtered_df['day'] == day\n",
                "    day_data = filtered_df[day_mask]\n",
                "    \n",
                "    if len(day_data) > 0:\n",
                "        max_popularity = day_data['popularity_score'].max()\n",
                "        if max_popularity > 0:\n",
                "            filtered_df.loc[day_mask, 'cluster_max_popularity'] = max_popularity\n",
                "            filtered_df.loc[day_mask, 'normalized_popularity'] = (\n",
                "                filtered_df.loc[day_mask, 'popularity_score'] / max_popularity\n",
                "            )\n",
                "        else:\n",
                "            filtered_df.loc[day_mask, 'cluster_max_popularity'] = 1.0\n",
                "            filtered_df.loc[day_mask, 'normalized_popularity'] = 0.5\n",
                "    \n",
                "print(\"📊 Normalized Popularity (per cluster):\")\n",
                "for day in range(1, NUM_DAYS + 1):\n",
                "    day_data = filtered_df[filtered_df['day'] == day]\n",
                "    if len(day_data) > 0:\n",
                "        print(f\"   Day {day}: range {day_data['normalized_popularity'].min():.3f} - {day_data['normalized_popularity'].max():.3f}\")\n",
                "\n",
                "print(f\"\\n✅ Popularity normalized within clusters\")"
            ]
        }
    ]

def add_module4_setup_cells():
    """Module 4 Setup: POI class and distance functions."""
    return [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 6. Module 4: Genetic Algorithm Route Optimization\n",
                "\n",
                "### 6.1 POI Class & Distance Functions"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "class POI:\n",
                "    \"\"\"Point of Interest with attributes for route planning.\"\"\"\n",
                "    \n",
                "    def __init__(self, name, lat, lon, normalized_popularity, \n",
                "                 place_id=None, rating=4.0, user_ratings_total=0, types=''):\n",
                "        self.name = name\n",
                "        self.lat = lat\n",
                "        self.lon = lon\n",
                "        self.normalized_popularity = normalized_popularity\n",
                "        self.place_id = place_id or name\n",
                "        self.rating = rating\n",
                "        self.user_ratings_total = user_ratings_total\n",
                "        \n",
                "        # Set opening/closing times and visit duration\n",
                "        self.opening_time = DEFAULT_OPENING_TIME\n",
                "        self.closing_time = DEFAULT_CLOSING_TIME\n",
                "        self.visit_duration_min = self._get_visit_duration(types)\n",
                "    \n",
                "    def _get_visit_duration(self, types):\n",
                "        \"\"\"Determine visit duration based on place type.\"\"\"\n",
                "        types_lower = str(types).lower()\n",
                "        for loc_type, duration in VISIT_DURATIONS.items():\n",
                "            if loc_type != 'default' and loc_type in types_lower:\n",
                "                return duration\n",
                "        return VISIT_DURATIONS['default']\n",
                "    \n",
                "    def __repr__(self):\n",
                "        return f\"POI({self.name[:30]}, WPI={self.normalized_popularity:.3f})\"\n",
                "\n",
                "\n",
                "def load_pois_for_day(df, day):\n",
                "    \"\"\"Load POI objects for a specific day.\"\"\"\n",
                "    day_data = df[df['day'] == day]\n",
                "    pois = []\n",
                "    for _, row in day_data.iterrows():\n",
                "        poi = POI(\n",
                "            name=row['name'],\n",
                "            lat=row['latitude'],\n",
                "            lon=row['longitude'],\n",
                "            normalized_popularity=row['normalized_popularity'],\n",
                "            place_id=row.get('place_id', row['name']),\n",
                "            rating=row['rating'],\n",
                "            user_ratings_total=row.get('user_ratings_total', 0),\n",
                "            types=row.get('types', '')\n",
                "        )\n",
                "        pois.append(poi)\n",
                "    return pois\n",
                "\n",
                "print('✅ POI class defined')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def haversine_distance(coord1, coord2):\n",
                "    \"\"\"\n",
                "    Calculate great-circle distance between two coordinates.\n",
                "    \n",
                "    Args:\n",
                "        coord1: (lat, lon) tuple\n",
                "        coord2: (lat, lon) tuple\n",
                "    \n",
                "    Returns:\n",
                "        Distance in kilometers\n",
                "    \"\"\"\n",
                "    lat1, lon1 = coord1\n",
                "    lat2, lon2 = coord2\n",
                "    \n",
                "    # Convert to radians\n",
                "    lat1, lon1, lat2, lon2 = map(radians, [lat1, lon1, lat2, lon2])\n",
                "    \n",
                "    # Haversine formula\n",
                "    dlat = lat2 - lat1\n",
                "    dlon = lon2 - lon1\n",
                "    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2\n",
                "    c = 2 * asin(sqrt(a))\n",
                "    \n",
                "    # Earth radius in kilometers\n",
                "    r = 6371\n",
                "    return c * r\n",
                "\n",
                "print('✅ Haversine distance function defined')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def get_osrm_distance_matrix(pois):\n",
                "    \"\"\"\n",
                "    Get distance/duration matrix from OSRM server.\n",
                "    \n",
                "    Args:\n",
                "        pois: List of POI objects\n",
                "    \n",
                "    Returns:\n",
                "        Tuple of (distance_matrix_km, duration_matrix_min) or None if OSRM unavailable\n",
                "    \"\"\"\n",
                "    if not osrm_available:\n",
                "        return None\n",
                "    \n",
                "    # Build coordinates string\n",
                "    coords_str = ';'.join([f\"{poi.lon},{poi.lat}\" for poi in pois])\n",
                "    url = f\"{OSRM_BASE_URL}/table/v1/driving/{coords_str}?annotations=distance,duration\"\n",
                "    \n",
                "    try:\n",
                "        response = requests.get(url, timeout=10)\n",
                "        if response.status_code == 200:\n",
                "            data = response.json()\n",
                "            \n",
                "            # Extract distance (meters) and duration (seconds)\n",
                "            distance_matrix = np.array(data['distances']) / 1000.0  # Convert to km\n",
                "            duration_matrix = np.array(data['durations']) / 60.0    # Convert to minutes\n",
                "            \n",
                "            return distance_matrix, duration_matrix\n",
                "    except Exception as e:\n",
                "        print(f\"⚠️  OSRM request failed: {e}\")\n",
                "    \n",
                "    return None\n",
                "\n",
                "print('✅ OSRM distance matrix function defined')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def build_distance_matrix(pois):\n",
                "    \"\"\"\n",
                "    Build distance and duration matrices for POIs.\n",
                "    Try OSRM first, fall back to haversine if unavailable.\n",
                "    \n",
                "    Args:\n",
                "        pois: List of POI objects\n",
                "    \n",
                "    Returns:\n",
                "        Tuple of (distance_matrix_km, duration_matrix_min, poi_index)\n",
                "    \"\"\"\n",
                "    n = len(pois)\n",
                "    \n",
                "    # Try OSRM\n",
                "    result = get_osrm_distance_matrix(pois)\n",
                "    if result is not None:\n",
                "        distance_matrix, duration_matrix = result\n",
                "        print(f\"   ✅ Using OSRM routing ({n}×{n} matrix)\")\n",
                "    else:\n",
                "        # Fall back to haversine\n",
                "        print(f\"   ⚠️  Using haversine fallback ({n}×{n} matrix)\")\n",
                "        distance_matrix = np.zeros((n, n))\n",
                "        duration_matrix = np.zeros((n, n))\n",
                "        \n",
                "        for i in range(n):\n",
                "            for j in range(n):\n",
                "                if i != j:\n",
                "                    dist_km = haversine_distance(\n",
                "                        (pois[i].lat, pois[i].lon),\n",
                "                        (pois[j].lat, pois[j].lon)\n",
                "                    )\n",
                "                    distance_matrix[i, j] = dist_km\n",
                "                    duration_matrix[i, j] = (dist_km / AVERAGE_SPEED_KM_H) * 60  # Convert to minutes\n",
                "    \n",
                "    # Build POI index mapping\n",
                "    poi_index = {poi.place_id: i for i, poi in enumerate(pois)}\n",
                "    \n",
                "    return distance_matrix, duration_matrix, poi_index\n",
                "\n",
                "\n",
                "def get_cached_distance(poi1, poi2):\n",
                "    \"\"\"Get distance between two POIs from cached matrix.\"\"\"\n",
                "    global CURRENT_DISTANCE_KM, CURRENT_POI_INDEX\n",
                "    \n",
                "    if CURRENT_DISTANCE_KM is None or CURRENT_POI_INDEX is None:\n",
                "        # Fall back to haversine\n",
                "        return haversine_distance((poi1.lat, poi1.lon), (poi2.lat, poi2.lon))\n",
                "    \n",
                "    i = CURRENT_POI_INDEX.get(poi1.place_id)\n",
                "    j = CURRENT_POI_INDEX.get(poi2.place_id)\n",
                "    \n",
                "    if i is not None and j is not None:\n",
                "        return CURRENT_DISTANCE_KM[i, j]\n",
                "    \n",
                "    return haversine_distance((poi1.lat, poi1.lon), (poi2.lat, poi2.lon))\n",
                "\n",
                "\n",
                "def calculate_travel_time(poi1, poi2):\n",
                "    \"\"\"Calculate travel time between two POIs from cached matrix.\"\"\"\n",
                "    global CURRENT_DURATION_MIN, CURRENT_POI_INDEX\n",
                "    \n",
                "    if CURRENT_DURATION_MIN is None or CURRENT_POI_INDEX is None:\n",
                "        # Fall back to speed-based calculation\n",
                "        dist_km = get_cached_distance(poi1, poi2)\n",
                "        return (dist_km / AVERAGE_SPEED_KM_H) * 60\n",
                "    \n",
                "    i = CURRENT_POI_INDEX.get(poi1.place_id)\n",
                "    j = CURRENT_POI_INDEX.get(poi2.place_id)\n",
                "    \n",
                "    if i is not None and j is not None:\n",
                "        return CURRENT_DURATION_MIN[i, j]\n",
                "    \n",
                "    dist_km = get_cached_distance(poi1, poi2)\n",
                "    return (dist_km / AVERAGE_SPEED_KM_H) * 60\n",
                "\n",
                "print('✅ Distance caching functions defined')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def time_to_minutes(time_str):\n",
                "    \"\"\"Convert HH:MM time string to minutes since midnight.\"\"\"\n",
                "    h, m = map(int, time_str.split(':'))\n",
                "    return h * 60 + m\n",
                "\n",
                "\n",
                "def minutes_to_time(minutes):\n",
                "    \"\"\"Convert minutes since midnight to HH:MM string.\"\"\"\n",
                "    h = int(minutes // 60)\n",
                "    m = int(minutes % 60)\n",
                "    return f\"{h:02d}:{m:02d}\"\n",
                "\n",
                "print('✅ Time conversion functions defined')\n",
                "print('\\n✅ Module 4 Setup complete')"
            ]
        }
    ]

# Continue in next file due to length...
print("Module builder functions defined")
